name: ci

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: cargo test
